name: CI

on:
  push:
  pull_requests:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, masos-latest, windows-latest]
        pytho-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12-dev"
          - "pypy-3.7"
          - "pypy-3.8"
          - "pypy-3.9"

    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      #import our code to github for test
      - name: Checkout code
        uses: actions/checkout@v3

      # sets up the  python enviroment
      - name: Set up Python
        uses: action/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      #install pytest
      - name: Install decendencies
        run: python -m pip install pytest .

      # running test
      - name: Run tests
        run: pytest
